services:
  - type: web
    name: whatsapp-gemini-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: PHONE_NUMBER_ID
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
